//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neko.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Neko - игра по изучению основ японского языка
        ///Игра состоит из трёх уровней: Хирагана, Катакана и Счёт
        ///Уровни Хирагана и Катакана одинаковы по своей структуре
        ///Начав любой из них вы попадёте на страницу с информацией о каждом слоге азбуки
        ///Далее вы можете пройти на страницу с информацией о правильном написании или 
        ///к выбору изучения желаемого ряда
        ///На странице выбора рада для изучения вы можите преключить режим игры
        ///Во всей игре имеется два режима: 
        ///1 - выбор написания к данному слогу(числу)
        ///2 - выбор слога(чис [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string aboutGame {
            get {
                return ResourceManager.GetString("aboutGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на あ/a/А
        ///い/i/И
        ///う/u/У
        ///え/e/Э
        ///お/o/О
        ///か/ka/Ка が/ga/Га
        ///き/ki/Ки ぎ/gi/Ги
        ///く/ku/Ку ぐ/gu/Гу
        ///け/ke/Кэ げ/ge/Гэ
        ///こ/ko/Ко ご/go/Го
        ///さ/sa/Са ざ/za/За
        ///し/shi/Си じ/ji/Дзи
        ///す/su/Су ず/zu/Зу
        ///せ/se/Сэ ぜ/ze/Зэ
        ///そ/so/Со ぞ/zo/Зо
        ///た/ta/Та だ/da/Да
        ///ち/ti/Ти ぢ/dzi/Дзи
        ///つ/tsu/Тсу づ/dzu/Дзу
        ///て/te/Тэ で/de/Дэ
        ///と/to/То ど/do/До
        ///な/na/На
        ///に/ni/Ни
        ///ぬ/nu/Ну
        ///ね/ne/Нэ
        ///の/no/Но
        ///は/ha/Ха ば/ba/Ба ぱ/pa/Па
        ///ひ/hi/Хи び/bi/Би ぴ/pi/Пи
        ///ふ/fu/Фу ぶ/bu/Бу ぷ/pu/Пу
        ///へ/he/Хэ べ/be/Бэ ぺ/pe/Пэ
        ///ほ/ho/Хо ぼ/bo/Хо ぽ/po/Хо
        ///ま/ma/Ма
        ///み/mi/Ми
        ///む/mu/Му
        ///め/me/Мэ
        ///も/mo/Мо
        ///や/ya/Я
        ///_/_
        ///ゆ/yu/Ю
        ///_/_
        ///よ/yo/Ё
        ///ら/ra/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Hiragana {
            get {
                return ResourceManager.GetString("Hiragana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HiraganaTable {
            get {
                object obj = ResourceManager.GetObject("HiraganaTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ア/a/А
        ///イ/i/И
        ///ウ/u/У
        ///エ/e/Э
        ///オ/o/О
        ///カ/ka/Ка ガ/ga/Га
        ///キ/ki/Ки ギ/gi/Ги
        ///ク/ku/Ку グ/gu/Гу
        ///ケ/ke/Кэ ゲ/ge/Гэ
        ///コ/ko/Ко ゴ/go/Го
        ///サ/sa/Са ザ/za/За
        ///シ/shi/Си ジ/ji/Дзи
        ///ス/su/Су ズ/zu/Зу
        ///セ/se/Сэ ゼ/ze/Зэ
        ///ソ/so/Со ゾ/zo/Зо
        ///タ/ta/Та ダ/da/Да
        ///チ/ti/Ти ヂ/dzi/Дзи
        ///ツ/tsu/Тсу ヅ/dzu/Дзу
        ///テ/te/Тэ デ/de/Дэ
        ///ト/to/То ド/do/До
        ///ナ/na/На
        ///ニ/ni/Ни
        ///ヌ/nu/Ну
        ///ネ/ne/Нэ
        ///ノ/no/Но
        ///ハ/ha/Ха バ/ba/Ба パ/pa/Па
        ///ヒ/hi/Хи ビ/bi/Би ピ/pi/Пи
        ///フ/fu/Фу ブ/bu/Бу プ/pu/Пу
        ///ヘ/he/Хэ ベ/be/Бэ ペ/pe/Пэ
        ///ホ/ho/Хо ボ/bo/Хо ポ/po/Хо
        ///マ/ma/Ма
        ///ミ/mi/Ми
        ///ム/mu/Му
        ///メ/me/Мэ
        ///モ/mo/Мо
        ///ヤ/ya/Я
        ///_/_
        ///ユ/yu/Ю
        ///_/_
        ///ヨ/yo/Ё
        ///ラ/ra/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Katakana {
            get {
                return ResourceManager.GetString("Katakana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KatakanaTable {
            get {
                object obj = ResourceManager.GetObject("KatakanaTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NekoLog {
            get {
                object obj = ResourceManager.GetObject("NekoLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon NekoLogIcon {
            get {
                object obj = ResourceManager.GetObject("NekoLogIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0_zero_零_дзэро
        ///1_ichi_一_ичи
        ///2_ni_二_ни
        ///3_san_三_сан
        ///4_yon/shi_四_ён/щи
        ///5_go_五_го
        ///6_roku_六_року
        ///7_nana/shichi_七_нана/сичи
        ///8_hachi_八_хачи
        ///9_kyu:/ku_九_кю:/ку
        ///10_ju:_十_дзю:
        ///11_ju: ichi_十一_дзю: ичи
        ///15_ju: go_十五_дзю: го
        ///20_ni-ju:_二十_ни дзю:
        ///37_san-ju: nana_三十七_сан дзю: нана
        ///42_yon-ju: ni_四十二_ён дзю: ни
        ///59_go-ju: kyu_五十九_го дзю: кю:
        ///68_roku-ju: hachi_六十八_року дзю: хачи
        ///76_nana-ju: roku_七十六_нана дзю: року
        ///83_hachi-ju: san_八十三_хачи дзю: сан
        ///94_kyu-ju: yon_九十四_кю: дзю: ён
        ///100_hyaku_百_хяку.
        /// </summary>
        internal static string Score_0_100 {
            get {
                return ResourceManager.GetString("Score_0_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100_hyaku_百_хяку
        ///123_hyaku ni-ju: san_百二十三_хяку ни дзю: сан
        ///200_ni hyaku_二百_ни хяку
        ///274_ni hyaku nana-ju: yon_二百七十四_ни хяку нана дзю: ён
        ///300_sam byaku_三百_cам бяку
        ///321_sam byaku ni-ju: ichi_三百二十一_сам бяку ни дзю: ичи
        ///400_yon hyaku_四百_ён хяку
        ///409_yon hyaku kyu:_四百九_ён хяку кю:
        ///473_yon hyaku nana-ju: san_四百七十三_ён хяку нана дзю: сан
        ///500_go hyaku_五百_го хяку
        ///551_go hyaku go-ju: ichi_五百五十一_го хяку го дзю: ичи
        ///600_roppyaku_六百_роппяку
        ///607_roppyaku nana_六百七_роппяку нана
        ///700_nana hyaku_七百_нана хяку
        ///758_nana hyaku go-j [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Score_100_1000 {
            get {
                return ResourceManager.GetString("Score_100_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1000_sen_千_cэн
        ///1200_sen ni hyaku_千二百_сэн ни хяку
        ///2000_ni sen_二千_ни сэн
        ///2045_ni sen yon-ju: go_二千四十五_ни сэн ён дзю:
        ///3000_san zen_三千_сан дзен
        ///3009_san zen kyu:_三千九_сан дзен кю:
        ///4000_yon sen_四千_ён сэн
        ///4444_yon sen yon hyaku yon-ju: yon_四千四百四十四_ён сэн ён хяку ён дзю:
        ///5000_go sen_五千_го сэн
        ///5308_go sen sam byaku hachi_五千三十八_го сэн сам бяку хачи
        ///8000_hassen_八千_хассен
        ///8375_hassen sam byaku nana-ju: go_八千三百七十五_хассен сам бяку нана  дзю: го
        ///9000_kyu: sen_九千_кю: сэн
        ///9933_kyu: sen kyu: hyaku san-ju: san_九千九百三十三_кю: сэн [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Score_1000_100000 {
            get {
                return ResourceManager.GetString("Score_1000_100000", resourceCulture);
            }
        }
    }
}
